const fs=require("fs"); const path=require("path"); const {loadSalon}=require("./validate");
const faqsPath=path.join(process.cwd(),"config","faqs.json"); const apptsPath=path.join(process.cwd(),"data","appointments.json");
function loadFaqs(){return JSON.parse(fs.readFileSync(faqsPath,"utf-8"))}
function matchFaq(t){t=t.toLowerCase(); for(const f of loadFaqs()){ if(f.tags.some(x=>t.includes(x.toLowerCase()))) return f.answer_template;} return null;}
function answerGeneral(){const s=loadSalon();return`Das habe ich leider nicht verstanden. Unser Salon heißt "${s.company_name}".`;}
function saveAppointment(a){try{const list=JSON.parse(fs.readFileSync(apptsPath,"utf-8")); list.push({...a,created_at:new Date().toISOString()}); fs.writeFileSync(apptsPath,JSON.stringify(list,null,2));}catch{}}
function intentFromText(t){t=t.toLowerCase(); if(["termin","buchen","vereinbaren"].some(x=>t.includes(x))) return"appointment"; if(matchFaq(t)) return"faq"; return"fallback";}
function collectAppointmentSlots(text,state={}){let s={...state}; const name=text.match(/(ich bin|mein name ist)\s+([a-zäöüß\- ]+)/i); if(!s.name&&name)s.name=name[2].trim(); const services=loadSalon().services.map(x=>x.name.toLowerCase()); for(const svc of services){ if(!s.service&&text.toLowerCase().includes(svc)) s.service=svc;} const date=text.match(/(20\d{2}-\d{2}-\d{2})/); const time=text.match(/([01]?\d|2[0-3]):([0-5]\d)/); if(!s.date&&date)s.date=date[1]; if(!s.time&&time)s.time=time[0]; const contact=text.match(/\S+@\S+\.\S+|\+?\d[\d\s\-\/]{6,}/); if(!s.contact&&contact)s.contact=contact[0];
const missing=[]; if(!s.name)missing.push("Name"); if(!s.service)missing.push("Service"); if(!s.date)missing.push("Datum"); if(!s.time)missing.push("Uhrzeit"); if(!s.contact)missing.push("Kontakt");
const complete=missing.length===0; return{slots:s,complete,nextPrompt:complete?"Soll ich senden?":`Fehlt noch: ${missing.join(", ")}`};}
module.exports={loadFaqs:()=>{},matchFaq,answerGeneral,saveAppointment,intentFromText,collectAppointmentSlots};